env:
  es2021: true
  node: true
extends:
  - google
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - eslint-config-prettier
  - eslint-config-prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'eslint-plugin-prettier'
rules: {}
