env:
  es2021: true
  node: true
extends:
  - google
  - eslint-config-prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - 'eslint-plugin-prettier'
rules: {}
